# Generated by Django 5.1.7 on 2025-04-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['option_id']},
        ),
        migrations.AddField(
            model_name='choice',
            name='option_id',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(help_text='Choice text (supports multiple lines)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Question text (supports multiple lines)'),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'option_id')},
        ),
    ]
