# Generated by Django 5.1.7 on 2025-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_choice_options_remove_answer_selected_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='randomize_choices',
            field=models.BooleanField(default=False, help_text='Keep this disabled to maintain A,B,C,D order'),
        ),
    ]
